# Generated by Django 2.2.3 on 2019-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flight", "0002_seat")]

    operations = [
        migrations.AlterField(
            model_name="flight", name="aircraft", field=models.CharField(max_length=100)
        )
    ]
