# Generated by Django 2.2.3 on 2019-07-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20190719_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='number',
            new_name='seat_number',
        ),
    ]
