# Generated by Django 2.2.3 on 2019-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authenticate", "0003_auto_20190717_0715")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
