# Generated by Django 2.2.3 on 2019-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authenticate", "0005_auto_20190718_0620")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
